# Generated by Django 3.2.4 on 2021-06-30 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-post_date'], 'verbose_name_plural': 'ブログ'},
        ),
        migrations.AlterModelOptions(
            name='blogauthor',
            options={'ordering': ['user', 'bio'], 'verbose_name_plural': 'ブログ著者'},
        ),
        migrations.AlterModelOptions(
            name='blogcomment',
            options={'ordering': ['-post_date'], 'verbose_name_plural': 'ブログコメント'},
        ),
    ]
